name: Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          path: kvelte
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.VPS_SECRET_KEY }}
          host: ${{secrets.VPS_HOST}}
          username: ${{secrets.VPS_USERNAME}}
          port: ${{secrets.VPS_SSH_PORT}}
          script: |
            whoami
            cd kvelte
            sh deploy.sh